apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: func-126-hybrid
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/min-scale: "1"
        autoscaling.knative.dev/max-scale: "5"
        autoscaling.knative.dev/target: "999"
        autoscaling.knative.dev/metric: "concurrency"
        autoscaling.knative.dev/window: "10s"
    spec:
      containers:
      - image: knativeacr25446.azurecr.io/forecasting-api:v8
        imagePullPolicy: Always
        name: forecasting
        env:
        - name: MODEL_TYPE
          value: "hybrid"
        - name: FUNCTION_ID
          value: "func_126"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "250m"
            memory: "512Mi"
